--1. 
SELECT PROFESSOR_NAME, PROFESSOR_ADDRESS
FROM TB_PROFESSOR
ORDER BY PROFESSOR_NAME;

--2. 
SELECT STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
ORDER BY EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM TO_DATE(SUBSTR(STUDENT_SSN, 1, 6), 'YYMMDD')) ASC;

-- 3. 
SELECT PROFESSOR_NAME,
           EXTRACT(YEAR FROM SYSDATE) - (19 || SUBSTR(PROFESSOR_SSN,1,2)) 나이
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN,8,1) = '1'
ORDER BY 나이;

-- 4.
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO = '005'
ORDER BY PROFESSOR_SSN;

-- 5.
/*
SELECT STUDENT_NO, POINT
FROM TB_GRADE
JOIN TB_CLASS ON TB_STUDENT.CLASS_ID = TB_CLASS.CLASS_ID
WHERE CLASS_NO = 'C3118100'
ORDER BY POINT DESC, STUDENT_NO ASC;
*/

-- 6.

-- 7.


-- 8.
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_PROFESSOR
JOIN TB_CLASS_PROFESSOR USING (PROFESSOR_NO)
JOIN TB_CLASS USING (CLASS_NO)
ORDER BY PROFESSOR_NAME;

-- 9.

-- 10.
SELECT G.STUDENT_NO 학번, STUDENT_NAME "학생 이름", ROUND(AVG(POINT),1) "전체 평점"
FROM TB_GRADE G
JOIN TB_STUDENT S ON (G.STUDENT_NO = S.STUDENT_NO)
JOIN TB_DEPARTMENT D ON (S.DEPARTMENT_NO = D.DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '음악학과'
GROUP BY G.STUDENT_NO, S.STUDENT_NAME;

-- 11.

-- 12.
SELECT STUDENT_NAME, TERM_NO AS TERM_NAME
FROM TB_STUDENT
JOIN TB_GRADE USING (CLASS_NO)
JOIN TB_CLASS USING (DEPARTMENT_NO)
WHERE TERM_NO LIKE '2007%'
    AND CLASS_NAME = '인간관계론';

-- 13.
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS
LEFT JOIN TB_CLASS_PROFESSOR USING (CLASS_NO)
LEFT JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE CATEGORY = '예체능'
    AND PROFESSOR_NO IS NULL;

-- 14.
SELECT STUDENT_NAME 학생이름, NVL(PROFESSOR_NAME, '지도교수 미지정') 지도교수
FROM TB_STUDENT S
LEFT JOIN TB_PROFESSOR ON (PROFESSOR_NO = COACH_PROFESSOR_NO)
JOIN TB_DEPARTMENT D ON (D.DEPARTMENT_NO = S.DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '서반아어학과'
ORDER BY STUDENT_NO;
    
-- 15.
SELECT STUDENT_NO 학번, STUDENT_NAME 이름,DEPARTMENT_NAME 학과이름, AVG(POINT) 평점
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
JOIN TB_GRADE USING (STUDENT_NO)
WHERE ABSENCE_YN = 'N'
GROUP BY STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
HAVING AVG(POINT) >= 4      --> GROUP에 대한 조건
ORDER BY 1;

-- 16.
SELECT CLASS_NO, CLASS_NAME, AVG(POINT)
FROM TB_CLASS
JOIN TB_GRADE USING (CLASS_NO)
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '환경조경학과'
    AND CLASS_TYPE LIKE '전공%'
GROUP BY CLASS_NO, CLASS_NAME
ORDER BY CLASS_NO;

-- 17. 

-- 18.
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
JOIN TB_GRADE USING (STUDENT_NO)
WHERE DEPARTMENT_NAME = '국어국문학과'
GROUP BY STUDENT_NO, STUDENT_NAME
HAVING AVG(POINT) = (SELECT MAX(AVG(POINT))
                                  FROM TB_GRADE
                                  JOIN TB_STUDENT USING (STUDENT_NO)
                                  JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
                                  WHERE DEPARTMENT_NAME = '국어국문학과'
                                 GROUP BY STUDENT_NO);

-- 19.
SELECT DEPARTMENT_NAME "계열 학과명", ROUND(AVG(POINT),1)
FROM TB_DEPARTMENT
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
JOIN TB_STUDENT USING (STUDENT_NO)
WHERE TB_CATERGORY = (SELECT CATEGORY
                               FROM TB_DEPARTMENT
                               WHERE DEPARTMENT_NAME = '환경조경학과')
GROUP BY DEPARTMENT_NAME
ORDER BY 1;

