--1. 
SELECT PROFESSOR_NAME, PROFESSOR_ADDRESS
FROM TB_PROFESSOR
ORDER BY PROFESSOR_NAME;

--2. 
SELECT STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
ORDER BY EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM TO_DATE(SUBSTR(STUDENT_SSN, 1, 6), 'YYMMDD')) ASC;

-- 3. 
SELECT PROFESSOR_NAME,
           EXTRACT(YEAR FROM SYSDATE) - (19 || SUBSTR(PROFESSOR_SSN,1,2)) 나이
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN,8,1) = '1'
ORDER BY 나이;

-- 4.
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO = '005'
ORDER BY PROFESSOR_SSN;

-- 5.
/*
SELECT STUDENT_NO, POINT
FROM TB_GRADE
JOIN TB_CLASS ON TB_STUDENT.CLASS_ID = TB_CLASS.CLASS_ID
WHERE CLASS_NO = 'C3118100'
ORDER BY POINT DESC, STUDENT_NO ASC;
*/

-- 6.

-- 7.


-- 8.
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_PROFESSOR
JOIN TB_CLASS_PROFESSOR USING (PROFESSOR_NO)
JOIN TB_CLASS USING (CLASS_NO)
ORDER BY PROFESSOR_NAME;

-- 9.

-- 10.

-- 11.

-- 12.

-- 13.

-- 14.

-- 15.
SELECT NVL(SUBSTR(TERM_NO,1,4), ' ') 년도, NVL(SUBSTR(TERM_NO,5,2), ' ') 학기, ROUND(AVG(POINT)) 평균
FROM TB_GRADE
WHERE STUDENT_NO='A112113'
GROUP BY ROLLUP(SUBSTR(TERM_NO,1,4), SUBSTR(TERM_NO,5,2))
ORDER BY 1;

-- 16.


