-- 1. 
INSERT ALL
    INTO TB_CLASS_TYPE (PK_CLASS_TYPE_NO, CLASS_TYPE_NAME) VALUES (01, '전공필수')
    INTO TB_CLASS_TYPE (PK_CLASS_TYPE_NO, CLASS_TYPE_NAME) VALUES (02, '전공선택')
    INTO TB_CLASS_TYPE (PK_CLASS_TYPE_NO, CLASS_TYPE_NAME) VALUES (03, '교양필수')
    INTO TB_CLASS_TYPE (PK_CLASS_TYPE_NO, CLASS_TYPE_NAME) VALUES (04, '교양선택')
    INTO TB_CLASS_TYPE (PK_CLASS_TYPE_NO, CLASS_TYPE_NAME) VALUES (05, '논문지도')
SELECT * FROM dual;

-- 2. 
CREATE TABLE TB_학생일반정보
AS SELECT STUDENT_NO, STUDENT_NAME, STUDENT_ADDRESS
     FROM TB_STUDENT;

-- 3.
CREATE TABLE TB_국어국문학과
AS SELECT  STUDENT_NO 학번, STUDENT_NAME 학생이름, SUBSTR(STUDENT_SSN,1,6) 생년월일, PROFESSOR_NAME 교수이름
     FROM TB_STUDENT S
     JOIN TB_PROFESSOR P ON (S.COACH_PROFESSOR_NO = P.PROFESSOR_NO)
     JOIN TB_DEPARTMENT D ON (S.DEPARTMENT_NO = D.DEPARTMENT_NO)
     WHERE DEPARTMENT_NAME = '국어국문학과';
     
-- 4. 


